version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:13
    restart: always
    environments:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/ini.sql:/docker-entrypoint-initdb.d/init.sql 